### ISSUE TITLE
Conflict with Elementor templates

### ISSUE THREAD

**Issue by lutifyme** [10up/safe-redirect-manager#160]
Hey guys,

First, a great plugin! I wrote this comment on the plugin support thread at wp.org, however I've noticed that recent threads there have gone unanswered for quite some time so I thought I would let you know about this here. If this is not the right place to report such thing, please delete this comment and accept my apologies.

Anyway, when safe redirect manager is used in combination with Elementor Pro plugin, this plugin causes conflict which causes a fatal error when trying to add a “single post” template (or 404 template, or any other non-page template) in Elementor Pro. The error is as following:

Fatal error: Uncaught Error: Call to a member function update_meta() on null in /wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:234 Stack trace: #0 /wp-content/plugins/elementor-pro/modules/theme-builder/documents/single.php(209): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(176857, Array) #1 /wp-content/plugins/elementor/core/documents-manager.php(387): ElementorPro\Modules\ThemeBuilder\Documents\Single->save_template_type() #2 /wp-content/plugins/elementor/core/admin/admin.php(641): Elementor\Core\Documents_Manager->create(‘single’, Array, Array) #3 /wp-includes/class-wp-hook.php(286): Elementor\Core\Admin\Admin->admin_action_new_post(”) #4 /wp-includes/class-wp-hook.php(310): WP_Hook->app in /wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php on line 234

I tested this by disabling all plugins and enabling one by one and can confirm that it's safe redirect manager that's causing this.

Hope you have a solution for this. Thanks!

Goran

**Comment by jeffpaul** [comment]
@renatonascalves @jameswburke looks like perhaps you had a fix downstream that resolved this?  Care to push that upstream here for others to benefit from?

**Comment by BhargavBhandari90** [comment]
Hi Plugin Author,

Seems like someone did commit but didn't raise PR. I can re-check the fix and send a PR for this if the issue is still valid.

**Comment by jeffpaul** [comment]
@BhargavBhandari90 that would be great, thanks!
